# Generated by Django 5.0.2 on 2024-02-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date_time',
            field=models.DateField(default=1, verbose_name='boshlanadigan kun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='end_time',
            field=models.TimeField(verbose_name='aperatsi tugash vaqti '),
        ),
        migrations.AlterField(
            model_name='operation',
            name='start_time',
            field=models.TimeField(verbose_name='aperatsi boshlanosh vaqti '),
        ),
    ]
