# Generated by Django 5.0.2 on 2024-02-17 14:41

import django.core.validators
import django.db.models.deletion
import main.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_address_alter_user_age_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='booked_room',
        ),
        migrations.AddField(
            model_name='room',
            name='booked_room',
            field=models.BooleanField(default=False, verbose_name=' xona bosh va banligi'),
        ),
        migrations.AlterField(
            model_name='about_hospital',
            name='address',
            field=models.CharField(max_length=55, verbose_name='manzil'),
        ),
        migrations.AlterField(
            model_name='about_hospital',
            name='desctiption',
            field=models.CharField(max_length=255, verbose_name='tarif'),
        ),
        migrations.AlterField(
            model_name='about_hospital',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator], verbose_name='elektiron manzil'),
        ),
        migrations.AlterField(
            model_name='about_hospital',
            name='happy_patient',
            field=models.IntegerField(verbose_name='hursand bemor'),
        ),
        migrations.AlterField(
            model_name='about_hospital',
            name='motto',
            field=models.CharField(max_length=55, verbose_name='shiyor'),
        ),
        migrations.AlterField(
            model_name='about_hospital',
            name='name',
            field=models.CharField(max_length=55, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='about_hospital',
            name='number_doctor',
            field=models.IntegerField(verbose_name='shifokor soni'),
        ),
        migrations.AlterField(
            model_name='about_hospital',
            name='open_data',
            field=models.DateField(verbose_name='ochilgan vqat'),
        ),
        migrations.AlterField(
            model_name='about_hospital',
            name='reting',
            field=models.FloatField(default=0, verbose_name='reting'),
        ),
        migrations.AlterField(
            model_name='casse',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='pul'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=25, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.TextField(verbose_name="o'zi haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='create_at',
            field=models.DateField(auto_now=True, verbose_name='yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.department', verbose_name="bo'lim"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_time',
            field=models.TimeField(verbose_name='ish tugatish vaqti'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.IntegerField(verbose_name='tajribasi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.room', verbose_name='xona'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='oylik'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_time',
            field=models.TimeField(verbose_name='ish boshlash vaqti'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('director', 'direcotor'), ('admin', 'admin'), ('manager', 'manager'), ('cooker', 'cooker'), ('doctor', 'doctor'), ('nurse', 'nurse')], max_length=25, verbose_name='lavozimi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='extra_info',
            field=models.TextField(verbose_name='malumot'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=55, verbose_name='ism'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='number',
            field=models.IntegerField(verbose_name='soni'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rooms',
            field=models.ManyToManyField(to='main.room', verbose_name='xona'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='create_at',
            field=models.DateField(auto_now=True, verbose_name='yaratilgan b-vaqt'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='doctors',
            field=models.ManyToManyField(to='main.employee', verbose_name='xodim'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='end_time',
            field=models.DateField(verbose_name='aperatsi tugash vaqti '),
        ),
        migrations.AlterField(
            model_name='operation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='bemor'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room', verbose_name='xona'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='start_time',
            field=models.DateField(verbose_name='aperatsi boshlanosh vaqti '),
        ),
        migrations.AlterField(
            model_name='patient',
            name='create_at',
            field=models.DateField(auto_now=True, verbose_name='yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='create_at',
            field=models.DateField(auto_now=True, verbose_name='yaratishgan vaqt'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='bemor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('full paid', 'full paid'), ('part paid', 'part paid'), ('unpaid', 'unpaid')], max_length=25, verbose_name='tolov turi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='shifokor'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='pul'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='create_at',
            field=models.DateField(auto_now=True, verbose_name='yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='sabab'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(verbose_name='sigimi'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity_status',
            field=models.CharField(choices=[('fre', 'free'), ('booked', 'booked')], max_length=25, verbose_name='capacity_status'),
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.department', verbose_name='bolim'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=25, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='room',
            name='other_info',
            field=models.TextField(verbose_name='malomot'),
        ),
        migrations.AlterField(
            model_name='testimonial_patient',
            name='create_at',
            field=models.DateField(auto_now=True, verbose_name='yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='testimonial_patient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='bemor'),
        ),
        migrations.AlterField(
            model_name='testimonial_patient',
            name='text',
            field=models.TextField(verbose_name='izoh'),
        ),
        migrations.AlterField(
            model_name='testimonial_patient',
            name='type_testimonial',
            field=models.CharField(choices=[('offer', 'offer'), ('complaint', 'complaint'), ('testimonial', 'testimonial')], max_length=25, verbose_name='izoh turi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='manzil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='yosh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_photo', validators=[main.validators.ImageFileValidator], verbose_name='hodim_rasmi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=25, null=True, verbose_name='jinsi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Invalid phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')], verbose_name='telefon raqam'),
        ),
    ]
