# Generated by Django 5.0.2 on 2024-02-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_employee_specialty_remove_patient_booked_room_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casse',
            new_name='Cassa',
        ),
    ]
